# Generated by Django 3.1.6 on 2021-02-18 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_auto_20210219_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='like_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
